[formatter.rust]
command  = "cargo"
options  = ["fmt", "--all", "--verbose", "--"]
includes = ["*.rs"]

[formatter.protobuf]
command = "sh"
options = ["-eucx", """
buf format --write
"""]
includes = ["*.proto"]

[formatter.protobuf-check]
command = "sh"
options = ["-eucx", """
buf format --exit-code
"""]
includes = ["*.proto"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
  "*.css",
  "*.html",
  "*.js",
  "*.json",
  "*.jsx",
  "*.md",
  "*.mdx",
  "*.scss",
  "*.ts",
  "*.yaml",
]

[formatter.toml]
command  = "taplo"
options  = ["format", "$@"]
includes = ["*.toml"]

[formatter.nix]
command  = "nixfmt"
includes = ["*.nix"]

[formatter.shell]
command = "sh"
options = ["-eucx", """
# Perform static analysis tool
shellcheck --external-sources --source-path=SCRIPTDIR "$@"

# Run formatter
shfmt --write --simplify --case-indent --indent 4 "$@"
    """, "--"]
includes = ["*.sh"]

[formatter.hcl]
command  = "hclfmt"
options  = ["-w"]
includes = ["*.hcl"]
