complete -c clipcat-notify -n "__fish_use_subcommand" -l no-clipboard -d 'Does not monitor clipboard'
complete -c clipcat-notify -n "__fish_use_subcommand" -l no-primary -d 'Does not monitor primary'
complete -c clipcat-notify -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c clipcat-notify -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c clipcat-notify -n "__fish_use_subcommand" -f -a "version" -d 'Prints version information'
complete -c clipcat-notify -n "__fish_use_subcommand" -f -a "completions" -d 'Outputs shell completion code for the specified shell (bash, zsh, fish)'
complete -c clipcat-notify -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c clipcat-notify -n "__fish_seen_subcommand_from version" -s h -l help -d 'Prints help information'
complete -c clipcat-notify -n "__fish_seen_subcommand_from version" -s V -l version -d 'Prints version information'
complete -c clipcat-notify -n "__fish_seen_subcommand_from completions" -s h -l help -d 'Prints help information'
complete -c clipcat-notify -n "__fish_seen_subcommand_from completions" -s V -l version -d 'Prints version information'
complete -c clipcat-notify -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c clipcat-notify -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
