complete -c clipcat-menu -n "__fish_use_subcommand" -s c -l config -d 'Specifies a configuration file'
complete -c clipcat-menu -n "__fish_use_subcommand" -s f -l finder -d 'Specifies a finder'
complete -c clipcat-menu -n "__fish_use_subcommand" -s m -l menu-length -d 'Specifies the menu length of finder'
complete -c clipcat-menu -n "__fish_use_subcommand" -s l -l line-length -d 'Specifies the length of a line showing on finder'
complete -c clipcat-menu -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c clipcat-menu -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c clipcat-menu -n "__fish_use_subcommand" -f -a "version" -d 'Prints version information'
complete -c clipcat-menu -n "__fish_use_subcommand" -f -a "completions" -d 'Outputs shell completion code for the specified shell (bash, zsh, fish)'
complete -c clipcat-menu -n "__fish_use_subcommand" -f -a "default-config" -d 'Outputs default configuration'
complete -c clipcat-menu -n "__fish_use_subcommand" -f -a "list-finder" -d 'Prints available text finders'
complete -c clipcat-menu -n "__fish_use_subcommand" -f -a "insert" -d 'Insert selected clip into clipboard'
complete -c clipcat-menu -n "__fish_use_subcommand" -f -a "insert-primary" -d 'Insert selected clip into primary clipboard'
complete -c clipcat-menu -n "__fish_use_subcommand" -f -a "remove" -d 'Removes selected clip'
complete -c clipcat-menu -n "__fish_use_subcommand" -f -a "edit" -d 'Edit selected clip'
complete -c clipcat-menu -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c clipcat-menu -n "__fish_seen_subcommand_from version" -s h -l help -d 'Prints help information'
complete -c clipcat-menu -n "__fish_seen_subcommand_from version" -s V -l version -d 'Prints version information'
complete -c clipcat-menu -n "__fish_seen_subcommand_from completions" -s h -l help -d 'Prints help information'
complete -c clipcat-menu -n "__fish_seen_subcommand_from completions" -s V -l version -d 'Prints version information'
complete -c clipcat-menu -n "__fish_seen_subcommand_from default-config" -s h -l help -d 'Prints help information'
complete -c clipcat-menu -n "__fish_seen_subcommand_from default-config" -s V -l version -d 'Prints version information'
complete -c clipcat-menu -n "__fish_seen_subcommand_from list-finder" -s h -l help -d 'Prints help information'
complete -c clipcat-menu -n "__fish_seen_subcommand_from list-finder" -s V -l version -d 'Prints version information'
complete -c clipcat-menu -n "__fish_seen_subcommand_from insert" -s h -l help -d 'Prints help information'
complete -c clipcat-menu -n "__fish_seen_subcommand_from insert" -s V -l version -d 'Prints version information'
complete -c clipcat-menu -n "__fish_seen_subcommand_from insert-primary" -s h -l help -d 'Prints help information'
complete -c clipcat-menu -n "__fish_seen_subcommand_from insert-primary" -s V -l version -d 'Prints version information'
complete -c clipcat-menu -n "__fish_seen_subcommand_from remove" -s h -l help -d 'Prints help information'
complete -c clipcat-menu -n "__fish_seen_subcommand_from remove" -s V -l version -d 'Prints version information'
complete -c clipcat-menu -n "__fish_seen_subcommand_from edit" -s e -l editor -d 'Specifies a external editor'
complete -c clipcat-menu -n "__fish_seen_subcommand_from edit" -s h -l help -d 'Prints help information'
complete -c clipcat-menu -n "__fish_seen_subcommand_from edit" -s V -l version -d 'Prints version information'
complete -c clipcat-menu -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c clipcat-menu -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
