complete -c clipcatd -n "__fish_use_subcommand" -s c -l config -d 'Specifies a configuration file'
complete -c clipcatd -n "__fish_use_subcommand" -l history-file -d 'Specifies a history file'
complete -c clipcatd -n "__fish_use_subcommand" -l grpc-host -d 'Specifies gRPC host address'
complete -c clipcatd -n "__fish_use_subcommand" -l grpc-port -d 'Specifies gRPC port number'
complete -c clipcatd -n "__fish_use_subcommand" -l no-daemon -d 'Does not run as daemon'
complete -c clipcatd -n "__fish_use_subcommand" -s r -l replace -d 'Tries to replace existing daemon'
complete -c clipcatd -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c clipcatd -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c clipcatd -n "__fish_use_subcommand" -f -a "version" -d 'Prints version information'
complete -c clipcatd -n "__fish_use_subcommand" -f -a "completions" -d 'Outputs shell completion code for the specified shell (bash, zsh, fish)'
complete -c clipcatd -n "__fish_use_subcommand" -f -a "default-config" -d 'Outputs default configuration'
complete -c clipcatd -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c clipcatd -n "__fish_seen_subcommand_from version" -s h -l help -d 'Prints help information'
complete -c clipcatd -n "__fish_seen_subcommand_from version" -s V -l version -d 'Prints version information'
complete -c clipcatd -n "__fish_seen_subcommand_from completions" -s h -l help -d 'Prints help information'
complete -c clipcatd -n "__fish_seen_subcommand_from completions" -s V -l version -d 'Prints version information'
complete -c clipcatd -n "__fish_seen_subcommand_from default-config" -s h -l help -d 'Prints help information'
complete -c clipcatd -n "__fish_seen_subcommand_from default-config" -s V -l version -d 'Prints version information'
complete -c clipcatd -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c clipcatd -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
